### ISSUE TITLE
Is it allowed to add third-party android apps which are installable on Sony?

### ISSUE THREAD

**Issue by KaraRyougi** [ma1co/OpenMemories-AppList#3]
CPU-Z works well on my a7, so I want to add CPU-Z in the list. But I wonder if that will cause any copyright issues?

**Comment by ma1co** [comment]
I don't think we should apps to the list which aren't designed for cameras.

However, I've added a new tab to the app store to search apkpure.com directly (download the newest release). Is that enough?

**Comment by KaraRyougi** [comment]
Since most of the apps designed for mobile phones won't work on a sony camera, I think we can list those working apps (which I believe are quite few...) A search tab is also great!

**Comment by tommiehansen** [comment]
Tried CPU-Z, it worked as expected. Pretty funny.

![CPU-Z running on A7r II](http://i.imgur.com/sNSpEoF.jpg)

So have anyone tried rooting it and doing some iffy stuff like undervolting (to decrease temps) or overclock? :-)

**Comment by tommiehansen** [comment]
Tried a bounch of other apps as well, most just crash. Basically there aren't any app that actually would be really useful on our cameras. The only benefit might be that some developer could fork some open source camera app for Android and "just" translate all function calls to instead use the Sony ones.
