### ISSUE TITLE
time lapse app

### ISSUE THREAD

**Issue by yassine-mahjoubi** [ma1co/OpenMemories-AppList#4]
hi and thank you for you efforts ,
it's possible to make the timelapse app from sony pkaymemories accessible for us (third world ) 

thank you much !

**Comment by FredM** [comment]
Same in Canada: impossible to even **buy** the Sony Time-lapse application ...

**Comment by ma1co** [comment]
Please try this app instead: https://github.com/jonasjuffinger/TimeLapse
